# ------------------------
# 389. Find the Difference
# ------------------------

# Problem: https://leetcode.com/problems/find-the-difference
#
# You are given two strings s and t.
# 
# String t is generated by random shuffling string s and then add one more letter
# at a random position.
# 
# Return the letter that was added to t.
# 
# Example 1:
# 
# Input: s = "abcd", t = "abcde"
# Output: "e"
# 
# Explanation: 'e' is the letter that was added.
# 
# Example 2:
# 
# Input: s = "", t = "y"
# Output: "y"
# 
# 
# Constraints:
#         0 <= s.length <= 1000
#         t.length == s.length + 1
#         s and t consist of lowercase English letters.

from collections import Counter

# Solution: https://youtu.be/oFmv4N4z00c
# Credit: Navdeep Singh founder of NeetCode
def find_the_difference_hash(s, t):
    # Hashmap solution
    count_s, count_t = Counter(s), Counter(t)
    for c in count_t:
        if c not in count_s:
            return c
        if count_s[c] < count_t[c]:
            return c
    # Time: O(n) 
    # Space: O(1)

def find_the_difference_ascii(s, t):
    # ASCII code solution
    sum_s, sum_t = 0, 0
    for c in s:
        sum_s += ord(c)
    for c in t:
        sum_t += ord(c)
    return chr(sum_t - sum_s)
    # Time: O(n) 
    # Space: O(1)

def find_the_difference(s, t):
    # Bit manipulation solution
    res = 0
    for c in s:
        res = res ^ ord(c)
    for c in t:
        res = res ^ ord(c)
    return chr(res)
    # Time: O(n) 
    # Space: O(1)

def main():
    result = find_the_difference(s = "abcd", t = "abcde")
    print(result) # "e"

    result = find_the_difference(s = "", t = "y")
    print(result) # "y"

if __name__ == "__main__":
    main()
