# -------------------------------------
# 1332. Remove Palindromic Subsequences
# -------------------------------------

# Problem: https://leetcode.com/problems/remove-palindromic-subsequences
#
# You are given a string s consisting only of letters 'a' and 'b'. In a single
# step you can remove one palindromic subsequence from s.
# 
# Return the minimum number of steps to make the given string empty.
# 
# A string is a subsequence of a given string if it is generated by deleting some
# characters of a given string without changing its order. Note that a subsequence
# does not necessarily need to be contiguous.
# 
# A string is called palindrome if is one that reads the same backward as well as
# forward.
# 
# Example 1:
# 
# Input: s = "ababa"
# Output: 1
# 
# Explanation: s is already a palindrome, so its entirety can be removed in a
# single step.
# 
# Example 2:
# 
# Input: s = "abb"
# Output: 2
# 
# Explanation: "abb" -> "bb" -> "".
# Remove palindromic subsequence "a" then "bb".
# 
# Example 3:
# 
# Input: s = "baabb"
# Output: 2
# 
# Explanation: "baabb" -> "b" -> "".
# Remove palindromic subsequence "baab" then "b".
# 
# 
# Constraints:
#         1 <= s.length <= 1000
#         s[i] is either 'a' or 'b'.


# Solution: https://algo.monster/liteproblems/1332
# Credit: AlgoMonster
def remove_palindrome_sub(s):
    # Check if the entire string is a palindrome
    # by comparing it with its reverse
    if s == s[::-1]:
        # If palindrome, we can remove the entire string in one operation
        return 1
    else:
        # If not palindrome, we need exactly 2 operations:
        # First remove all 'a's (forms a palindromic subsequence)
        # Then remove all 'b's (forms another palindromic subsequence)
        return 2
    # Time: O(n)
    # Space: O(n)


def main():
    result = remove_palindrome_sub(s = "ababa")
    print(result) # True

    result = remove_palindrome_sub(s = "abb")
    print(result) # True

    result = remove_palindrome_sub(s = "baabb")
    print(result) # False

if __name__ == "__main__":
    main()
